# Generated by Django 6.0.1 on 2026-01-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_alter_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notes', verbose_name='Доп. файл'),
        ),
    ]
